### PR TITLE
Add Output for Account Not Found

### PR DESCRIPTION
**Pull request by mastenp**
Added a line of output when an account is not found

### CODE REVIEW

**Comment by averagesecurityguy** [comment]
You don't need the try...except block here. It is sufficient to just print the message. Also, I don't think you need the \n in the string.

**Comment by mastenp** [comment]
I will re-test without the Try Except, but couldn't get it to run without it.  

For the \n it just spaces out the printed result to prevent it from getting lost on the screen in the run command, especially if you only have a single result. 

As a new coder I appreciate the feedback.

**Comment by mastenp** [comment]
I went back and checked the code, I was able to remove the Try/Except.  The \n is an appearance thing for single runs, but I see how it could be problematic on a run of say 100 emails, with 25 of them suddenly having a blank line separating them.

**Comment by averagesecurityguy** [comment]
Changes look good. Thank you for your contribution.

**Pull request merged**
